export const MATH_TAXONOMY = [
  {
    id: 'foundations',
    label: 'Foundations',
    description: 'Foundations, Logic & Meta-Mathematics',
    subfields: [
      { id: 'set-theory', name: 'Set Theory', role: 'A common universe for mathematical objects and a theory of infinity.', topics: ['ZFC', 'ordinals', 'cardinals', 'axiom of choice', 'forcing', 'large cardinals', 'determinacy', 'descriptive set theory', 'inner models', 'combinatorial set theory'] },
      { id: 'proof-theory', name: 'Proof Theory', role: 'Analyzes proofs as mathematical objects.', topics: ['formal calculi', 'sequent calculus', 'cut elimination', 'ordinal analysis', 'consistency strength', 'proof mining', 'reverse mathematics'] },
      { id: 'model-theory', name: 'Model Theory', role: 'Studies mathematical structures through formal languages.', topics: ['structures', 'theories', 'types', 'stability theory', 'o-minimality', 'ultraproducts', 'nonstandard analysis', 'finite model theory'] },
      { id: 'computability', name: 'Computability Theory', role: 'Classifies what can and cannot be computed.', topics: ['Turing machines', 'recursive functions', 'degrees of unsolvability', 'undecidability', 'arithmetical hierarchy', 'algorithmic randomness'] },
      { id: 'category-theory', name: 'Category Theory', role: 'A language of structure-preserving maps and universal properties.', topics: ['categories', 'functors', 'natural transformations', 'limits and colimits', 'adjunctions', 'monads', 'toposes', 'enriched categories'] },
      { id: 'type-theory', name: 'Type Theory', role: 'A foundation connecting logic, programs, and proofs.', topics: ['dependent types', 'linear type theory', 'cubical type theory', 'homotopy type theory', 'Curry–Howard correspondence', 'Martin-Löf type theory'] },
      { id: 'formal-proof', name: 'Formalized Mathematics', role: 'Makes proofs machine-checkable and increasingly searchable.', topics: ['proof assistants', 'Lean', 'Coq', 'Isabelle', 'automated theorem proving', 'interactive theorem proving', 'proof libraries'] },
      { id: 'foundations-alt', name: 'Foundational Alternatives', role: 'Different philosophies and formal bases for mathematics.', topics: ['constructivism', 'intuitionism', 'predicativism', 'finitism', 'univalent foundations', 'category-theoretic foundations'] },
    ],
  },
  {
    id: 'algebra',
    label: 'Algebra',
    description: 'Algebra & Algebraic Structures',
    subfields: [
      { id: 'linear-algebra', name: 'Linear Algebra', role: 'The basic language of linear structure.', topics: ['vector spaces', 'matrices', 'determinants', 'rank', 'eigenvalues', 'canonical forms', 'inner products', 'spectral theorem', 'singular value decomposition'] },
      { id: 'multilinear-algebra', name: 'Multilinear Algebra', role: 'Describes interactions among multiple linear variables.', topics: ['tensor products', 'exterior algebra', 'symmetric algebra', 'bilinear forms', 'tensor calculus', 'wedge products'] },
      { id: 'group-theory', name: 'Group Theory', role: 'Abstract theory of symmetry.', topics: ['finite groups', 'permutation groups', 'Sylow theory', 'solvable groups', 'simple groups', 'profinite groups', 'group actions', 'classification of finite simple groups'] },
      { id: 'lie-theory', name: 'Lie Groups & Lie Algebras', role: 'Symmetry with differentiable or algebraic structure.', topics: ['Lie groups', 'Lie algebras', 'root systems', 'semisimple Lie algebras', 'algebraic groups', 'compact groups', 'representation theory of Lie algebras'] },
      { id: 'ring-theory', name: 'Ring Theory', role: 'Algebraic systems with addition and multiplication.', topics: ['commutative rings', 'noncommutative rings', 'ideals', 'Noetherian rings', 'Artinian rings', 'local rings', 'principal ideal domains'] },
      { id: 'field-theory', name: 'Field Theory', role: 'The algebraic setting for solving equations.', topics: ['field extensions', 'finite fields', 'separability', 'algebraic closure', 'valuations', 'local fields', 'p-adic numbers'] },
      { id: 'galois-theory', name: 'Galois Theory', role: 'Links equations with symmetry groups.', topics: ['Galois groups', 'solvability by radicals', 'inverse Galois problem', 'differential Galois theory', 'étale fundamental group'] },
      { id: 'module-theory', name: 'Module Theory', role: 'Linear algebra over rings.', topics: ['modules', 'exact sequences', 'projective modules', 'injective modules', 'free modules', 'localization'] },
      { id: 'commutative-algebra', name: 'Commutative Algebra', role: 'Algebraic engine behind algebraic geometry and number theory.', topics: ['primary decomposition', 'Krull dimension', 'regular sequences', 'local cohomology', 'Cohen–Macaulay rings', 'Noetherian rings', 'flatness'] },
      { id: 'homological-algebra', name: 'Homological Algebra', role: 'Measures failure of exactness and organizes algebraic invariants.', topics: ['chain complexes', 'Ext', 'Tor', 'derived functors', 'spectral sequences', 'derived categories', 'triangulated categories'] },
      { id: 'representation-theory', name: 'Representation Theory', role: 'Studies algebraic objects through linear actions.', topics: ['characters', 'highest weight theory', 'quivers', 'Schur–Weyl duality', 'modular representations', 'Kazhdan–Lusztig theory'] },
      { id: 'universal-algebra', name: 'Universal Algebra', role: 'Studies algebraic systems uniformly.', topics: ['varieties', 'equational logic', 'clones', 'algebraic theories', 'Birkhoff theorem'] },
      { id: 'higher-algebra', name: 'Higher Algebra', role: 'Algebra with coherent higher homotopies.', topics: ['∞-categories', 'operads', 'En-algebras', 'derived algebra', 'spectral algebra', 'DAG'] },
    ],
  },
  {
    id: 'number-theory',
    label: 'Number Theory',
    description: 'Number Theory & Arithmetic',
    subfields: [
      { id: 'elementary-nt', name: 'Elementary Number Theory', role: 'Classical arithmetic of integers.', topics: ['divisibility', 'Euclidean algorithm', 'congruences', 'quadratic reciprocity', 'arithmetic functions', 'continued fractions', 'prime numbers'] },
      { id: 'algebraic-nt', name: 'Algebraic Number Theory', role: 'Uses algebra to study arithmetic extensions.', topics: ['number fields', 'rings of integers', 'ideal class groups', 'units', 'ramification', 'local fields', 'Dedekind domains', 'class field theory'] },
      { id: 'analytic-nt', name: 'Analytic Number Theory', role: 'Uses analysis to study arithmetic distribution.', topics: ['Riemann zeta function', 'L-functions', 'prime number theorem', 'sieve methods', 'exponential sums', 'circle method', 'Dirichlet series'] },
      { id: 'diophantine', name: 'Diophantine Equations', role: 'Solves polynomial equations over arithmetic domains.', topics: ['elliptic curves', 'local-global principles', 'descent', 'heights', 'Fermat\'s last theorem', 'Faltings theorem'] },
      { id: 'arithmetic-geometry', name: 'Arithmetic Geometry', role: 'Treats arithmetic problems geometrically.', topics: ['schemes over integers', 'rational points', 'abelian varieties', 'Galois representations', 'motives', 'étale cohomology', 'p-adic Hodge theory'] },
      { id: 'modular-forms', name: 'Modular & Automorphic Forms', role: 'Connects harmonic analysis, geometry, and arithmetic.', topics: ['modular forms', 'Maass forms', 'automorphic representations', 'trace formula', 'Langlands program', 'Hecke operators', 'L-functions'] },
      { id: 'additive-nt', name: 'Additive Number Theory', role: 'Studies additive patterns in numbers.', topics: ['Goldbach conjecture', 'Waring problem', 'sumsets', 'arithmetic progressions', 'additive combinatorics', 'Fourier analysis on groups'] },
      { id: 'multiplicative-nt', name: 'Multiplicative Number Theory', role: 'Studies multiplication-driven arithmetic phenomena.', topics: ['arithmetic functions', 'Dirichlet series', 'divisor problems', 'multiplicative number theory', 'Euler products'] },
      { id: 'transcendental-nt', name: 'Transcendental Number Theory', role: 'Determines when numbers are algebraic or transcendental.', topics: ['transcendence', 'irrationality', 'Diophantine approximation', 'Baker\'s theorem', 'periods', 'Schanuel conjecture'] },
      { id: 'computational-nt', name: 'Computational Number Theory', role: 'Arithmetic algorithms and cryptographic computation.', topics: ['primality testing', 'integer factorization', 'discrete logarithm', 'lattice reduction', 'elliptic curve cryptography'] },
    ],
  },
  {
    id: 'geometry',
    label: 'Geometry',
    description: 'Geometry',
    subfields: [
      { id: 'euclidean', name: 'Euclidean Geometry', role: 'Classical metric geometry of flat space.', topics: ['distances', 'angles', 'congruence', 'similarity', 'circles', 'polygons', 'transformations', 'Pythagorean theorem'] },
      { id: 'affine', name: 'Affine Geometry', role: 'Geometry without angles or lengths.', topics: ['parallelism', 'affine transformations', 'barycentric coordinates', 'convex combinations', 'affine independence'] },
      { id: 'projective', name: 'Projective Geometry', role: 'Geometry of perspective and points at infinity.', topics: ['incidence', 'duality', 'projective transformations', 'cross-ratio', 'projective varieties', 'homogeneous coordinates'] },
      { id: 'differential-geometry', name: 'Differential Geometry', role: 'Calculus on curved spaces.', topics: ['smooth manifolds', 'tangent bundles', 'vector fields', 'differential forms', 'connections', 'curvature', 'Lie derivatives'] },
      { id: 'riemannian', name: 'Riemannian Geometry', role: 'Geometry of length, angle, and curvature.', topics: ['Riemannian metrics', 'geodesics', 'curvature tensors', 'comparison theorems', 'holonomy', 'sectional curvature', 'Ricci flow'] },
      { id: 'lorentzian', name: 'Lorentzian Geometry', role: 'Geometry underlying relativity.', topics: ['spacetime manifolds', 'causal structure', 'geodesic completeness', 'singularity theorems', 'Penrose diagrams'] },
      { id: 'algebraic-geometry', name: 'Algebraic Geometry', role: 'Geometry of polynomial equations.', topics: ['varieties', 'schemes', 'sheaves', 'cohomology', 'divisors', 'moduli spaces', 'stacks', 'intersection theory', 'Hodge theory'] },
      { id: 'complex-geometry', name: 'Complex Geometry', role: 'Geometry over complex coordinates.', topics: ['complex manifolds', 'holomorphic bundles', 'several complex variables', 'analytic spaces', 'GAGA principle'] },
      { id: 'kahler', name: 'Kähler Geometry', role: 'Intersection of complex, symplectic, and Riemannian geometry.', topics: ['Kähler metrics', 'Hodge decomposition', 'Calabi–Yau manifolds', 'Ricci curvature', 'moment maps', 'Calabi conjecture'] },
      { id: 'symplectic', name: 'Symplectic Geometry', role: 'Geometry of phase space and area-type structure.', topics: ['symplectic manifolds', 'Hamiltonian systems', 'moment maps', 'Floer theory', 'contact geometry', 'Lagrangian submanifolds'] },
      { id: 'convex', name: 'Convex Geometry', role: 'Geometry of convex sets and inequalities.', topics: ['convex bodies', 'polytopes', 'Brunn–Minkowski theory', 'isoperimetry', 'high-dimensional convexity', 'John ellipsoid'] },
      { id: 'discrete-geometry', name: 'Discrete & Computational Geometry', role: 'Finite geometric configurations and computation.', topics: ['arrangements', 'triangulations', 'Voronoi diagrams', 'packing', 'tiling', 'geometric algorithms', 'Delaunay triangulation'] },
      { id: 'metric-geometry', name: 'Metric Geometry', role: 'Geometry using distance as primitive data.', topics: ['geodesic spaces', 'CAT(k) spaces', 'Alexandrov spaces', 'Gromov–Hausdorff convergence', 'coarse geometry'] },
    ],
  },
  {
    id: 'topology',
    label: 'Topology',
    description: 'Topology',
    subfields: [
      { id: 'point-set', name: 'Point-Set Topology', role: 'Foundational language of continuity.', topics: ['open sets', 'compactness', 'connectedness', 'separation axioms', 'products', 'quotients', 'compactifications', 'Stone–Čech compactification'] },
      { id: 'algebraic-topology', name: 'Algebraic Topology', role: 'Uses algebraic invariants to distinguish spaces.', topics: ['fundamental groups', 'covering spaces', 'homology', 'cohomology', 'spectral sequences', 'Euler characteristic', 'Poincaré duality'] },
      { id: 'homotopy-theory', name: 'Homotopy Theory', role: 'Studies spaces and maps up to deformation.', topics: ['homotopy groups', 'CW complexes', 'spectra', 'stable homotopy', 'model categories', '∞-categories', 'chromatic homotopy'] },
      { id: 'differential-topology', name: 'Differential Topology', role: 'Topology of differentiable manifolds.', topics: ['smooth manifolds', 'transversality', 'Morse theory', 'cobordism', 'surgery', 'exotic smooth structures', 'h-cobordism theorem'] },
      { id: 'geometric-topology', name: 'Geometric Topology', role: 'Topology informed by geometric models.', topics: ['manifold decompositions', 'triangulations', 'isotopy', 'geometric structures', 'Thurston geometrization'] },
      { id: 'low-dimensional', name: 'Low-Dimensional Topology', role: 'Special topology of dimensions three and four.', topics: ['3-manifolds', '4-manifolds', 'Heegaard splittings', 'Dehn surgery', 'gauge invariants', 'Floer homology', 'Donaldson theory'] },
      { id: 'knot-theory', name: 'Knot & Link Theory', role: 'Topology of embedded circles and links.', topics: ['knot groups', 'knot polynomials', 'braids', 'tangles', 'quantum invariants', 'categorification', 'Jones polynomial', 'Khovanov homology'] },
      { id: 'topological-groups', name: 'Topological Groups', role: 'Combines algebraic and topological structure.', topics: ['Lie groups', 'profinite groups', 'locally compact groups', 'Haar measure', 'Pontryagin duality'] },
      { id: 'applied-topology', name: 'Applied Topology', role: 'Topological methods for data and systems.', topics: ['persistent homology', 'mapper algorithm', 'sheaves on data', 'sensor networks', 'configuration spaces', 'TDA'] },
    ],
  },
  {
    id: 'analysis',
    label: 'Analysis',
    description: 'Analysis',
    subfields: [
      { id: 'real-analysis', name: 'Real Analysis', role: 'Rigorous theory of real functions.', topics: ['sequences', 'limits', 'continuity', 'differentiation', 'Riemann integration', 'Lebesgue integration', 'uniform convergence'] },
      { id: 'measure-theory', name: 'Measure Theory', role: 'General theory of size and integration.', topics: ['measures', 'measurable functions', 'Lebesgue integral', 'convergence theorems', 'product measures', 'Radon–Nikodym theorem'] },
      { id: 'functional-analysis', name: 'Functional Analysis', role: 'Linear analysis in infinite dimensions.', topics: ['Banach spaces', 'Hilbert spaces', 'locally convex spaces', 'duality', 'compactness', 'Hahn–Banach', 'open mapping theorem'] },
      { id: 'operator-theory', name: 'Operator Theory', role: 'Studies transformations of function spaces.', topics: ['bounded operators', 'unbounded operators', 'spectra', 'C*-algebras', 'von Neumann algebras', 'Fredholm theory'] },
      { id: 'complex-analysis', name: 'Complex Analysis', role: 'Analysis over complex numbers.', topics: ['holomorphic functions', 'residues', 'conformal maps', 'analytic continuation', 'Riemann surfaces', 'Cauchy integral formula'] },
      { id: 'several-complex', name: 'Several Complex Variables', role: 'Complex analysis in higher dimension.', topics: ['domains of holomorphy', 'pseudoconvexity', 'CR geometry', 'sheaf cohomology', 'Stein manifolds'] },
      { id: 'harmonic-analysis', name: 'Harmonic Analysis', role: 'Decomposes functions into frequencies or symmetries.', topics: ['Fourier analysis', 'singular integrals', 'wavelets', 'Hardy spaces', 'BMO', 'Calderón–Zygmund theory', 'Littlewood–Paley theory'] },
      { id: 'potential-theory', name: 'Potential Theory', role: 'Analysis of potentials and Laplace-type equations.', topics: ['harmonic functions', 'Green functions', 'capacity', 'boundary value problems', 'subharmonic functions'] },
      { id: 'distributions', name: 'Distribution Theory', role: 'Handles singular objects and weak solutions.', topics: ['generalized functions', 'weak derivatives', 'Sobolev spaces', 'microlocal analysis', 'pseudodifferential operators'] },
      { id: 'geometric-measure', name: 'Geometric Measure Theory', role: 'Combines measure, geometry, and variational analysis.', topics: ['rectifiability', 'currents', 'varifolds', 'minimal surfaces', 'Hausdorff measure', 'area formula'] },
      { id: 'approximation-theory', name: 'Approximation Theory', role: 'Approximates complicated functions by simpler ones.', topics: ['polynomial approximation', 'splines', 'orthogonal polynomials', 'rational approximation', 'Jackson theorem', 'Bernstein inequality'] },
    ],
  },
  {
    id: 'equations',
    label: 'Equations & Dynamics',
    description: 'Differential Equations & Dynamical Systems',
    subfields: [
      { id: 'ode', name: 'Ordinary Differential Equations', role: 'Finite-dimensional continuous-time dynamics.', topics: ['existence and uniqueness', 'stability', 'bifurcation', 'qualitative theory', 'flows', 'Poincaré maps', 'Sturm–Liouville theory'] },
      { id: 'pde', name: 'Partial Differential Equations', role: 'Equations involving functions of several variables.', topics: ['elliptic PDE', 'parabolic PDE', 'hyperbolic PDE', 'dispersive equations', 'nonlinear PDE', 'Navier–Stokes', 'Schrödinger equation'] },
      { id: 'calculus-variations', name: 'Calculus of Variations', role: 'Optimization over functions and shapes.', topics: ['Euler–Lagrange equations', 'direct methods', 'regularity', 'Γ-convergence', 'isoperimetric problems', 'minimal surfaces'] },
      { id: 'dynamical-systems', name: 'Dynamical Systems', role: 'Long-term evolution of deterministic systems.', topics: ['flows', 'maps', 'invariant sets', 'bifurcations', 'chaos', 'attractors', 'symbolic dynamics', 'Lyapunov exponents'] },
      { id: 'ergodic-theory', name: 'Ergodic Theory', role: 'Statistical behavior of deterministic dynamics.', topics: ['measure-preserving systems', 'recurrence', 'mixing', 'entropy', 'orbit equivalence', 'Birkhoff theorem', 'multiple recurrence'] },
      { id: 'geometric-analysis', name: 'Geometric Analysis', role: 'Uses PDE to solve geometric problems.', topics: ['Ricci flow', 'mean curvature flow', 'harmonic maps', 'minimal surfaces', 'Yang–Mills', 'Seiberg–Witten equations'] },
      { id: 'control-systems', name: 'Control Systems', role: 'Dynamics shaped by inputs and feedback.', topics: ['controllability', 'observability', 'stabilization', 'optimal control', 'Pontryagin maximum principle', 'LQR', 'Kalman filter'] },
    ],
  },
  {
    id: 'probability',
    label: 'Probability & Statistics',
    description: 'Probability, Statistics & Information',
    subfields: [
      { id: 'probability-theory', name: 'Probability Theory', role: 'Mathematics of random phenomena.', topics: ['random variables', 'distributions', 'expectation', 'independence', 'law of large numbers', 'central limit theorem', 'characteristic functions'] },
      { id: 'stochastic-processes', name: 'Stochastic Processes', role: 'Random objects indexed by time or space.', topics: ['Markov chains', 'Brownian motion', 'martingales', 'Lévy processes', 'Gaussian processes', 'random fields', 'Poisson processes'] },
      { id: 'stochastic-calculus', name: 'Stochastic Calculus', role: 'Calculus for random paths.', topics: ['Itô integral', 'stochastic differential equations', 'semimartingales', 'diffusions', 'Girsanov theorem', 'Feynman–Kac formula'] },
      { id: 'random-structures', name: 'Random Structures', role: 'Probability on combinatorial or algebraic objects.', topics: ['random graphs', 'percolation', 'interacting particle systems', 'random matrices', 'Erdős–Rényi model'] },
      { id: 'mathematical-statistics', name: 'Mathematical Statistics', role: 'Principles of inference from data.', topics: ['estimation', 'hypothesis testing', 'sufficiency', 'decision theory', 'asymptotic statistics', 'robustness', 'Cramér–Rao bound'] },
      { id: 'bayesian-statistics', name: 'Bayesian Statistics', role: 'Inference through probability updating.', topics: ['prior distributions', 'posterior inference', 'hierarchical models', 'MCMC', 'variational Bayes', 'Bayesian decision theory'] },
      { id: 'causal-inference', name: 'Causal Inference', role: 'Mathematical language of cause and effect.', topics: ['potential outcomes', 'graphical models', 'DAGs', 'identification', 'instrumental variables', 'do-calculus', 'counterfactuals'] },
      { id: 'information-theory', name: 'Information Theory', role: 'Quantifies information and communication limits.', topics: ['entropy', 'channel capacity', 'data compression', 'rate distortion', 'mutual information', 'Shannon theorem', 'error-correcting codes'] },
      { id: 'learning-theory', name: 'Learning Theory', role: 'Mathematical foundations of machine learning.', topics: ['PAC learning', 'VC dimension', 'generalization bounds', 'concentration inequalities', 'kernel methods', 'online learning', 'boosting'] },
      { id: 'high-dimensional-stats', name: 'High-Dimensional Statistics', role: 'Inference when dimension is large.', topics: ['sparsity', 'LASSO', 'random projections', 'compressed sensing', 'covariance estimation', 'random matrix theory'] },
    ],
  },
  {
    id: 'discrete',
    label: 'Discrete Math',
    description: 'Discrete Mathematics & Combinatorics',
    subfields: [
      { id: 'graph-theory', name: 'Graph Theory', role: 'Mathematics of vertices and edges.', topics: ['connectivity', 'coloring', 'matching', 'planarity', 'graph minors', 'spectral graph theory', 'random graphs', 'Ramsey theory'] },
      { id: 'enumerative-combinatorics', name: 'Enumerative Combinatorics', role: 'Counts discrete structures.', topics: ['generating functions', 'bijections', 'recurrences', 'partitions', 'symmetric functions', 'Catalan numbers', 'Stirling numbers'] },
      { id: 'extremal-combinatorics', name: 'Extremal Combinatorics', role: 'Determines maximum or minimum sizes under constraints.', topics: ['Turán theory', 'Ramsey theory', 'extremal set theory', 'Kruskal–Katona theorem', 'VC dimension'] },
      { id: 'probabilistic-combinatorics', name: 'Probabilistic Combinatorics', role: 'Uses randomness to prove combinatorial phenomena.', topics: ['probabilistic method', 'Lovász local lemma', 'concentration inequalities', 'random discrete structures'] },
      { id: 'algebraic-combinatorics', name: 'Algebraic Combinatorics', role: 'Applies algebra to combinatorial structure.', topics: ['posets', 'Möbius inversion', 'association schemes', 'symmetric functions', 'Young tableaux', 'Robinson–Schensted–Knuth'] },
      { id: 'additive-combinatorics', name: 'Additive Combinatorics', role: 'Studies additive patterns in groups and numbers.', topics: ['sumsets', 'arithmetic progressions', 'Freiman theorem', 'higher-order Fourier analysis', 'Szemerédi theorem', 'Green–Tao theorem'] },
      { id: 'matroid-theory', name: 'Matroid Theory', role: 'Abstracts linear and graphic independence.', topics: ['independence axioms', 'representability', 'matroid minors', 'oriented matroids', 'greedoids', 'matroid intersection'] },
      { id: 'coding-theory', name: 'Coding Theory', role: 'Reliable communication through redundancy.', topics: ['linear codes', 'cyclic codes', 'algebraic-geometric codes', 'LDPC codes', 'polar codes', 'list decoding', 'Shannon capacity'] },
      { id: 'design-theory', name: 'Design Theory', role: 'Highly regular finite incidence structures.', topics: ['block designs', 'balanced incomplete block designs', 'Steiner systems', 'Latin squares', 'finite geometries'] },
      { id: 'finite-geometry', name: 'Finite Geometry', role: 'Geometry over finite fields.', topics: ['projective planes', 'affine spaces over finite fields', 'polar spaces', 'incidence structures', 'caps and arcs'] },
    ],
  },
  {
    id: 'computation',
    label: 'Computation',
    description: 'Algorithms, Computation & Cryptography',
    subfields: [
      { id: 'algorithms', name: 'Algorithms', role: 'Designs efficient computational procedures.', topics: ['sorting', 'searching', 'graph algorithms', 'randomized algorithms', 'approximation algorithms', 'streaming algorithms', 'divide and conquer'] },
      { id: 'complexity', name: 'Computational Complexity', role: 'Classifies resource requirements of problems.', topics: ['P vs NP', 'NP-completeness', 'reductions', 'circuit complexity', 'space complexity', 'proof complexity', 'derandomization'] },
      { id: 'fine-grained-complexity', name: 'Parameterized & Fine-Grained Complexity', role: 'Measures complexity beyond classical polynomial time.', topics: ['fixed-parameter tractability', 'kernelization', 'ETH conjecture', 'conditional lower bounds', 'W-hierarchy'] },
      { id: 'quantum-computation', name: 'Quantum Computation', role: 'Computation using quantum systems.', topics: ['qubits', 'quantum circuits', 'Shor algorithm', 'Grover algorithm', 'quantum error correction', 'quantum complexity', 'BQP'] },
      { id: 'symbolic-computation', name: 'Symbolic Computation', role: 'Exact manipulation of mathematical expressions.', topics: ['Gröbner bases', 'computer algebra', 'exact arithmetic', 'polynomial factoring', 'algebraic algorithms'] },
      { id: 'cryptography', name: 'Cryptography', role: 'Secure computation and communication.', topics: ['public-key cryptography', 'symmetric encryption', 'digital signatures', 'zero-knowledge proofs', 'lattice cryptography', 'post-quantum cryptography'] },
      { id: 'computational-geometry-alg', name: 'Computational Geometry', role: 'Algorithms for geometric objects.', topics: ['convex hulls', 'triangulations', 'nearest neighbors', 'geometric data structures', 'motion planning'] },
      { id: 'formal-methods', name: 'Formal Methods', role: 'Mathematical verification of hardware, software, and proofs.', topics: ['model checking', 'SAT solvers', 'SMT solvers', 'program verification', 'Hoare logic', 'temporal logic'] },
    ],
  },
  {
    id: 'numerics',
    label: 'Numerics',
    description: 'Numerical & Computational Mathematics',
    subfields: [
      { id: 'numerical-linear-algebra', name: 'Numerical Linear Algebra', role: 'Computes with large linear systems and operators.', topics: ['matrix factorizations', 'LU decomposition', 'QR decomposition', 'iterative solvers', 'conditioning', 'eigenvalue algorithms', 'Krylov methods'] },
      { id: 'numerical-pde', name: 'Numerical PDE', role: 'Approximates differential equations.', topics: ['finite differences', 'finite elements', 'finite volumes', 'spectral methods', 'adaptive methods', 'multigrid', 'discontinuous Galerkin'] },
      { id: 'numerical-optimization', name: 'Numerical Optimization', role: 'Computational methods for optimization problems.', topics: ['gradient descent', 'Newton methods', 'interior point methods', 'stochastic gradient descent', 'proximal methods', 'ADMM'] },
      { id: 'approximation-interpolation', name: 'Approximation & Interpolation', role: 'Represents functions numerically.', topics: ['splines', 'polynomial interpolation', 'rational approximation', 'radial basis functions', 'Chebyshev approximation'] },
      { id: 'scientific-computing', name: 'Scientific Computing', role: 'Computational practice for scientific models.', topics: ['high-performance computing', 'simulation', 'uncertainty quantification', 'parallel computing', 'GPU computing'] },
      { id: 'computational-statistics-num', name: 'Computational Statistics', role: 'Algorithms for statistical inference.', topics: ['Monte Carlo methods', 'MCMC', 'bootstrap', 'variational inference', 'sequential Monte Carlo', 'importance sampling'] },
      { id: 'validated-numerics', name: 'Validated Numerics', role: 'Produces numerical results with rigorous error guarantees.', topics: ['interval arithmetic', 'a posteriori estimates', 'certified computation', 'computer-assisted proofs'] },
    ],
  },
  {
    id: 'optimization',
    label: 'Optimization',
    description: 'Optimization, Operations Research & Decision Mathematics',
    subfields: [
      { id: 'linear-programming', name: 'Linear Programming', role: 'Optimizes linear objectives under linear constraints.', topics: ['simplex method', 'LP duality', 'sensitivity analysis', 'network flows', 'polyhedra', 'complementary slackness'] },
      { id: 'convex-optimization', name: 'Convex Optimization', role: 'Optimization with global structure.', topics: ['convex sets', 'strong duality', 'subgradients', 'proximal methods', 'conic programming', 'semidefinite programming', 'ADMM'] },
      { id: 'nonlinear-optimization', name: 'Nonlinear Optimization', role: 'General smooth and nonsmooth optimization.', topics: ['KKT conditions', 'Newton methods', 'constrained optimization', 'nonsmooth optimization', 'augmented Lagrangian'] },
      { id: 'integer-optimization', name: 'Integer & Combinatorial Optimization', role: 'Optimization over discrete choices.', topics: ['integer programming', 'branch and bound', 'cutting planes', 'matchings', 'matroids', 'submodularity'] },
      { id: 'stochastic-optimization', name: 'Stochastic Optimization', role: 'Optimization under uncertainty.', topics: ['stochastic programming', 'recourse models', 'chance constraints', 'stochastic approximation', 'robust optimization'] },
      { id: 'operations-research', name: 'Operations Research', role: 'Mathematics of organized systems and operations.', topics: ['queuing theory', 'inventory theory', 'scheduling', 'logistics', 'simulation', 'decision analysis'] },
      { id: 'control-theory', name: 'Control Theory', role: 'Steers dynamic systems.', topics: ['feedback control', 'stability', 'optimal control', 'robust control', 'stochastic control', 'nonlinear control', 'LQR', 'MPC'] },
      { id: 'game-theory', name: 'Game Theory', role: 'Mathematics of strategic interaction.', topics: ['Nash equilibria', 'cooperative games', 'mechanism design', 'evolutionary games', 'repeated games', 'zero-sum games', 'auction theory'] },
      { id: 'mathematical-economics', name: 'Mathematical Economics', role: 'Mathematical structure of economic decisions.', topics: ['general equilibrium', 'social choice', 'dynamic programming', 'contract theory', 'matching theory'] },
    ],
  },
  {
    id: 'applied',
    label: 'Applied Math',
    description: 'Applied Mathematics & Mathematical Modeling',
    subfields: [
      { id: 'continuum-mechanics', name: 'Continuum Mechanics', role: 'Models matter as continuous media.', topics: ['elasticity', 'plasticity', 'conservation laws', 'constitutive models', 'stress and strain', 'deformation'] },
      { id: 'fluid-dynamics', name: 'Fluid Dynamics', role: 'Mathematics of liquids and gases.', topics: ['Euler equations', 'Navier–Stokes equations', 'turbulence', 'boundary layers', 'vorticity', 'multiphase flow', 'aerodynamics'] },
      { id: 'solid-mechanics', name: 'Solid Mechanics & Materials', role: 'Mathematics of deformation and material behavior.', topics: ['elasticity theory', 'fracture mechanics', 'homogenization', 'microstructure', 'materials modeling', 'viscoelasticity'] },
      { id: 'math-biology', name: 'Mathematical Biology', role: 'Models living systems.', topics: ['population dynamics', 'epidemiology', 'ecology', 'evolution', 'genetics', 'physiology', 'reaction-diffusion systems'] },
      { id: 'math-neuroscience', name: 'Mathematical Neuroscience', role: 'Mathematics of nervous systems.', topics: ['neural dynamics', 'neural networks', 'neural coding', 'stochastic spiking', 'Hodgkin–Huxley model', 'brain rhythms'] },
      { id: 'financial-math', name: 'Financial Mathematics', role: 'Mathematics of markets and risk.', topics: ['asset pricing', 'Black–Scholes', 'hedging', 'stochastic control', 'interest rate models', 'risk measures', 'market microstructure'] },
      { id: 'signal-processing', name: 'Signal & Image Processing', role: 'Extracts and transforms information from signals.', topics: ['Fourier methods', 'wavelets', 'sparsity', 'filtering', 'reconstruction', 'compressed sensing', 'inverse problems'] },
      { id: 'network-science', name: 'Network Science', role: 'Models connected systems.', topics: ['graph dynamics', 'spreading processes', 'synchronization', 'centrality measures', 'multilayer networks', 'community detection'] },
      { id: 'data-driven-modeling', name: 'Data-Driven Modeling', role: 'Combines data, computation, and mathematical structure.', topics: ['reduced-order models', 'system identification', 'scientific machine learning', 'physics-informed neural networks', 'DMD', 'SINDy'] },
    ],
  },
  {
    id: 'math-physics',
    label: 'Math Physics',
    description: 'Mathematical Physics',
    subfields: [
      { id: 'classical-mechanics-phys', name: 'Classical Mechanics', role: 'Mathematical structure of motion.', topics: ['Hamiltonian mechanics', 'Lagrangian mechanics', 'symplectic geometry', 'integrable systems', 'action-angle variables', 'KAM theory'] },
      { id: 'relativity', name: 'Relativity', role: 'Geometry of spacetime and gravitation.', topics: ['Einstein equations', 'Lorentzian geometry', 'black holes', 'cosmology', 'causal structure', 'singularity theorems'] },
      { id: 'quantum-mechanics-phys', name: 'Quantum Mechanics', role: 'Mathematical structure of microscopic physics.', topics: ['Hilbert spaces', 'spectral theory', 'self-adjoint operators', 'symmetries', 'scattering theory', 'quantum groups'] },
      { id: 'statistical-mechanics', name: 'Statistical Mechanics', role: 'Links microscopic randomness and macroscopic laws.', topics: ['Gibbs measures', 'phase transitions', 'Ising model', 'thermodynamic limit', 'renormalization group', 'critical phenomena'] },
      { id: 'qft', name: 'Quantum Field Theory', role: 'Fields, particles, and interactions.', topics: ['path integrals', 'renormalization', 'operator algebras', 'constructive QFT', 'axiomatic QFT', 'conformal field theory'] },
      { id: 'gauge-theory', name: 'Gauge Theory', role: 'Geometry of fields and topology of manifolds.', topics: ['connections', 'curvature', 'Yang–Mills', 'instantons', 'Donaldson theory', 'Seiberg–Witten theory', 'Chern–Simons theory'] },
      { id: 'string-theory', name: 'String Theory & Mirror Symmetry', role: 'Physical ideas generating geometric mathematics.', topics: ['Calabi–Yau manifolds', 'moduli spaces', 'mirror symmetry', 'Gromov–Witten theory', 'string dualities'] },
      { id: 'integrable-systems', name: 'Integrable Systems', role: 'Exactly solvable nonlinear systems.', topics: ['solitons', 'Lax pairs', 'inverse scattering', 'Painlevé equations', 'quantum groups', 'Bethe ansatz'] },
      { id: 'noncommutative-geometry', name: 'Noncommutative Geometry', role: 'Geometry where coordinates do not commute.', topics: ['operator algebras', 'spectral triples', 'cyclic cohomology', 'quantum spaces', 'Connes distance'] },
    ],
  },
  {
    id: 'emerging',
    label: 'Emerging Areas',
    description: 'Interdisciplinary & Emerging Areas',
    subfields: [
      { id: 'arithmetic-geometry-em', name: 'Arithmetic Geometry', role: 'Rational points and arithmetic spaces.', topics: ['cohomological methods', 'Galois representations', 'p-adic methods', 'perfectoid spaces', 'prismatic cohomology'] },
      { id: 'geometric-rep-theory', name: 'Geometric Representation Theory', role: 'Represents algebra through geometric categories.', topics: ['perverse sheaves', 'D-modules', 'character sheaves', 'geometric Langlands', 'Springer theory'] },
      { id: 'tda', name: 'Topological Data Analysis', role: 'Persistent qualitative structure in data.', topics: ['persistent homology', 'barcodes', 'Reeb graphs', 'mapper', 'Wasserstein distance', 'stability theorems'] },
      { id: 'random-matrix-theory', name: 'Random Matrix Theory', role: 'Eigenvalue statistics of random operators.', topics: ['GUE', 'GOE', 'Wigner semicircle law', 'Tracy–Widom distribution', 'universality', 'free probability'] },
      { id: 'math-ml', name: 'Mathematical Machine Learning', role: 'Why and when learning algorithms work.', topics: ['overparameterization', 'implicit regularization', 'neural tangent kernel', 'loss landscape geometry', 'generalization theory'] },
      { id: 'quantum-information', name: 'Quantum Information', role: 'Information processing using quantum systems.', topics: ['quantum entanglement', 'quantum channels', 'quantum error correction', 'quantum complexity', 'tensor networks', 'quantum Shannon theory'] },
      { id: 'complex-systems', name: 'Complex Systems', role: 'Collective behavior of many interacting components.', topics: ['emergence', 'self-organization', 'phase transitions', 'criticality', 'agent-based models', 'network dynamics'] },
      { id: 'math-climate', name: 'Mathematics of Climate', role: 'Mathematical structure of Earth systems.', topics: ['climate PDE', 'energy balance models', 'tipping points', 'uncertainty quantification', 'data assimilation'] },
      { id: 'formal-proof-ai', name: 'Formal Proof & AI for Mathematics', role: 'Machine-checkable and machine-assisted mathematics.', topics: ['autoformalization', 'LLMs for mathematics', 'neural theorem proving', 'AlphaProof', 'Lean', 'Mathlib'] },
    ],
  },
];
